name: Upload Component to ESP Registry

on:
  release:
    types: [published]  # Trigger when a release is manually published on GitHub

jobs:
  upload_component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Upload component to ESP Component Registry
        uses: espressif/upload-components-ci-action@v1
        with:
          namespace: 'sinricpro'
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
